# Generated by Django 3.2.4 on 2021-06-17 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmwork',
            options={'ordering': ['title'], 'verbose_name': 'filmwork', 'verbose_name_plural': 'filmwork'},
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='created',
            field=models.DateField(default=datetime.date.today, verbose_name='creation date'),
        ),
    ]
