version: '3.4'

services:
  etl:
    build:
      context: .
      dockerfile: ./compose/etl/Dockerfile
    container_name: etl_service
    depends_on:
      - postgres
      - elasticsearch
    env_file:
      - ./.envs/etl.env

  postgres:
    image: postgres:13
    container_name: etl_postgres
    volumes:
    - pg_data:/var/lib/postgresql/data
    - ./pg_dump.sql:/pg_dump.sql
    env_file:
      - ./.envs/postgres.env
    environment:
      - POSTGRES_PASSWORD=1234

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    container_name: etl_es
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"

  redis:
    image: redis:6-buster
    container_name: etl_redis

volumes:
  pg_data:
